services:
  postgres_db:
      image: postgres:latest
      container_name: postgres_container
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: MyPassword
        POSTGRES_DB: mydb
      volumes:
        - postgres_data:/data/postgres_db


volumes:
  postgres_data:
    driver: local