services:
  postgres_db:
      image: postgres:latest
      container_name: postgres_container
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: MyPassword
        POSTGRES_DB: mydb
      volumes:
        - postgres_data:/data/postgres_db

  liquibase:
    image: liquibase/liquibase
    depends_on:
      - postgres_db
    volumes:
      - ../app/migrations:/liquibase/changelog
    command: --defaults-file=/liquibase/changelog/liquibase.properties update

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
      - redis
    environment:
      - DATABASE_URL=postgresql+asyncpg://root:MyPassword@postgres_db/mydb
      - REDIS_HOST=redis

volumes:
  postgres_data:
    driver: local
  redis_data: